/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Instrument = IDL.Text;
export const Amount = IDL.Nat;
export const Balance = IDL.Nat;
export const Price = IDL.Nat;
export const Asset = IDL.Record({
  'id' : Instrument,
  'currentPrice' : Price,
  'openingPrice' : Price,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Timestamp = IDL.Nat;
export const TradeAmount = IDL.Nat;
export const Trade = IDL.Record({
  'instrument' : Instrument,
  'timestamp' : Timestamp,
  'tradeAmount' : TradeAmount,
  'price' : Price,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'buy' : IDL.Func([Instrument, Amount], [Balance], []),
  'createUser' : IDL.Func([], [], []),
  'deposit' : IDL.Func([Balance], [Balance], []),
  'getAllCurrentAssetPrices' : IDL.Func([], [IDL.Vec(Asset)], ['query']),
  'getCallerBalance' : IDL.Func([], [Balance], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallersInvestmentPortfolio' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Instrument, Amount))],
      ['query'],
    ),
  'getPrice' : IDL.Func([IDL.Text], [Price], []),
  'getTradeHistory' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sell' : IDL.Func([Instrument, Amount], [Balance], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Instrument = IDL.Text;
  const Amount = IDL.Nat;
  const Balance = IDL.Nat;
  const Price = IDL.Nat;
  const Asset = IDL.Record({
    'id' : Instrument,
    'currentPrice' : Price,
    'openingPrice' : Price,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Timestamp = IDL.Nat;
  const TradeAmount = IDL.Nat;
  const Trade = IDL.Record({
    'instrument' : Instrument,
    'timestamp' : Timestamp,
    'tradeAmount' : TradeAmount,
    'price' : Price,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'buy' : IDL.Func([Instrument, Amount], [Balance], []),
    'createUser' : IDL.Func([], [], []),
    'deposit' : IDL.Func([Balance], [Balance], []),
    'getAllCurrentAssetPrices' : IDL.Func([], [IDL.Vec(Asset)], ['query']),
    'getCallerBalance' : IDL.Func([], [Balance], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallersInvestmentPortfolio' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Instrument, Amount))],
        ['query'],
      ),
    'getPrice' : IDL.Func([IDL.Text], [Price], []),
    'getTradeHistory' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sell' : IDL.Func([Instrument, Amount], [Balance], []),
  });
};

export const init = ({ IDL }) => { return []; };