/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Amount = bigint;
export interface Asset {
  'id' : Instrument,
  'currentPrice' : Price,
  'openingPrice' : Price,
}
export type Balance = bigint;
export type Instrument = string;
export type Price = bigint;
export type Timestamp = bigint;
export interface Trade {
  'instrument' : Instrument,
  'timestamp' : Timestamp,
  'tradeAmount' : TradeAmount,
  'price' : Price,
}
export type TradeAmount = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'buy' : ActorMethod<[Instrument, Amount], Balance>,
  'createUser' : ActorMethod<[], undefined>,
  'deposit' : ActorMethod<[Balance], Balance>,
  'getAllCurrentAssetPrices' : ActorMethod<[], Array<Asset>>,
  'getCallerBalance' : ActorMethod<[], Balance>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallersInvestmentPortfolio' : ActorMethod<
    [],
    Array<[Instrument, Amount]>
  >,
  'getPrice' : ActorMethod<[string], Price>,
  'getTradeHistory' : ActorMethod<[], Array<Trade>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sell' : ActorMethod<[Instrument, Amount], Balance>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];